Feature/pn 1051
pagopa/pn-external-registries pull request #10
Opened 2022-04-16 10:42 UTC by MassimilianoAndriotto

Inserito gestione exception.

2022-04-29 17:23 UTC, MTurraPpa requested changes
Ho modificato il file _Integrazione-PNDNmd_ per rispecchiare il formato markdown.
Ho fatto diverse annotazioni al codice, mi premono in particolare quelle relative ai log, sia per il livello giusto di log che per le informazioni riportate. Poi sarà più semplice vederlo quando potremmo far girare il codice, ma già con i test si capisce qualcosa.
I test di integrazione dovrebbero funzionare anche in locale.
Attenzione all'utilizzo delle catch exception. Sarebbe sempre meglio fare il catch delle eccezioni specifiche e gestirle eventualmente rilanciandole con una nostra.

2022-05-02 08:51 UTC, MassimilianoAndriotto commented on src/main/java/it/pagopa/pn/external/registries/pdnd/utils/AssertionGenerator.java
> +        log.info("AWS config "+ awsConfig);
Fix: dump KeyARN in log file

2022-05-02 09:01 UTC, MassimilianoAndriotto commented on src/main/java/it/pagopa/pn/external/registries/pdnd/utils/AssertionGenerator.java
> +                log.info(kmsClient.toString());
changed log message

2022-05-03 08:10 UTC, MTurraPpa commented on .gitignore
> +/src/test/resources/nt-gateway.jks
Forse questo è scappato per errore?

2022-05-03 12:25 UTC, MassimilianoAndriotto commented on src/main/java/it/pagopa/pn/external/registries/pdnd/utils/AssertionGenerator.java
> +            log.info("jwtContent= " + jwtContent);
La variabile jwtContent deve essere utilizzata anche dopo perchè a questa deve essere concatenata la firma. Mi sembra che creare un metodo per fare un encoder di header e payload sia un po' troppo prolisso.

2022-05-03 12:26 UTC, MassimilianoAndriotto commented on src/main/java/it/pagopa/pn/external/registries/pdnd/utils/AssertionGenerator.java
> +            log.error("Error creating client_assertion: -> "+ e.getMessage() + " - " + e);
Hai ragione. Corretto.

2022-05-03 12:27 UTC, MassimilianoAndriotto commented on src/main/java/it/pagopa/pn/external/registries/pdnd/utils/AssertionGenerator.java
> +            log.info("Sign -> " + jwtSignature);
Duplicazione inutile. corretto

2022-05-04 08:55 UTC, MassimilianoAndriotto commented on src/main/java/it/pagopa/pn/external/registries/pdnd/utils/AssertionGenerator.java
> +            log.info("jwtContent= " + jwtContent);
eseguito il refactoring sulla PN-1269

2022-05-04 08:56 UTC, MassimilianoAndriotto commented on src/main/java/it/pagopa/pn/external/registries/pdnd/utils/AssertionGenerator.java
> +        } catch (Exception e) {
corretto il problema

2022-05-04 08:56 UTC, MassimilianoAndriotto commented on src/main/java/it/pagopa/pn/external/registries/pdnd/utils/AssertionGenerator.java
> +            long ttlMillis = 86400000; // 24 ore
Parametro portato all'interno del file di configurazione

2022-05-04 08:57 UTC, MassimilianoAndriotto commented on src/main/java/it/pagopa/pn/external/registries/pdnd/client/PDNDClient.java
> +            throw new Exception("Error creating assertion: " + e.getMessage());
Corretto il problema

2022-05-04 08:58 UTC, MassimilianoAndriotto commented on src/main/java/it/pagopa/pn/external/registries/pdnd/client/PDNDClient.java
> +        HttpClient httpClient = HttpClient.create().option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 1000)
fatto

2022-05-04 09:02 UTC, MassimilianoAndriotto commented on src/main/java/it/pagopa/pn/external/registries/pdnd/dto/TokenCacheEntry.java
> +    public boolean isExpired() {
Corretto in PN-1269

2022-05-04 09:03 UTC, MassimilianoAndriotto commented on src/main/java/it/pagopa/pn/external/registries/pdnd/dto/TokenCacheEntry.java
> +        expiresIn = clientCredential.getExpiresIn() * 1000 + System.currentTimeMillis();
corretto

2022-05-04 09:08 UTC, MassimilianoAndriotto commented on src/test/java/it/pagopa/pn/external/registries/pdnd/client/PDNDClientTestIT.java
> +        }catch(Exception e)
Fix PN-1269

2022-05-04 09:12 UTC, MassimilianoAndriotto commented on src/test/java/it/pagopa/pn/external/registries/pdnd/client/PDNDClientTestIT.java
> +            String header = new String(decoder.decode(chunks[0]));
Fatto in PN-1269

2022-05-17 06:57 UTC, marco-vit-pagopa approved these changes
Ok

2022-05-17 07:30 UTC, marco-vit-pagopa commented on src/main/java/it/pagopa/pn/external/registries/pdnd/dto/TokenCacheEntry.java
> +    public boolean isExpired() {
fatto anche in questo branch

2022-05-17 07:33 UTC, marco-vit-pagopa commented on src/main/java/it/pagopa/pn/external/registries/config/aws/AwsServicesClientsConfig.java
> +            System.setProperty( "aws.accessKeyId", props.getAccessKeyId() );
fixed

2022-05-17 07:33 UTC, marco-vit-pagopa commented on src/main/java/it/pagopa/pn/external/registries/pdnd/service/AccessTokenCacheService.java
> +                    TokenCacheEntry tok = new TokenCacheEntry("purposeId");
fatto

2022-05-17 07:34 UTC, marco-vit-pagopa commented on src/main/java/it/pagopa/pn/external/registries/pdnd/service/AccessTokenCacheService.java
> +            accessTokenHolder.put(purposeId, accessToken);
refactoring in cui è stato corretto anche tale aspetto

2022-05-17 08:37 UTC, MTurraPpa approved these changes

2022-05-17 08:53 UTC, merged