Feature/pn 4453
pagopa/pn-external-registries pull request #127
Opened 2023-03-02 14:49 UTC by fdammassa

2023-03-03 16:55 UTC, marco-vit-pagopa requested changes

2023-03-03 16:55 UTC, marco-vit-pagopa commented on codegen/config.json
> +    ]
Va aggiunto il check di presenza del bundle

2023-03-03 16:55 UTC, marco-vit-pagopa commented on docs/openapi/pn-selfcare-internal-v1.yaml
> +  '/ext-registry-b2b/pa/v1/groups':
Me lo aspettavo in un file il cui nome finale sia b2b analiziamo con comodo settimana prossima

2023-03-04 11:02 UTC, fdammassa commented on docs/openapi/pn-selfcare-internal-v1.yaml
> +  '/ext-registry-b2b/pa/v1/groups':
@marco-vit-pagopa abbiamo deciso insieme di lasciarlo in questo file perché in alternativa il code generator avrebbe dovuto duplicare diverse classi.
Tuttavia, in ottica di generazione del bundle, questo è un problema perché verrebbero inclusi anche altri metodi di questo file.
Proposta è aggiungere un altro "commento" del tipo "# NO_BUNDLE#

2023-03-04 11:02 UTC, fdammassa commented on codegen/config.json
> +    ]
@marco-vit-pagopa non l'ho aggiunto perché il bundle ancora non viene generato per via del linter fallito.

2023-03-07 08:58 UTC, marco-vit-pagopa approved these changes

2023-03-07 08:58 UTC, merged