API Selfcare UserGroup per PG
pagopa/pn-external-registries pull request #134
Opened 2023-03-22 09:51 UTC by SimoneMartelliNTTD

2023-03-22 10:17 UTC, SimoneMartelliNTTD commented
La configurazione della nuova API non è completa; è necessario:

- base URL di Selfcare PG
- API Key

Per quanto riguarda productId (prod-pn-dev) e uid (pn-m2m) ho assunto gli stessi per Selfcare PA.

2023-03-28 06:48 UTC, federicofatica-pagopa commented on docs/wsclient/selfcare/selc-external-v2.yaml
Questa modifica è relativa ad un aggiornamento lato Selfcare?

2023-03-28 08:34 UTC, SimoneMartelliNTTD commented on docs/wsclient/selfcare/selc-external-v2.yaml
È stata ripristinata la versione precedente dell'openapi in quanto la modifica dei tag per generare due client API non è strettamente necessaria.

2023-04-14 08:43 UTC, marco-vit-pagopa requested changes

2023-04-14 08:43 UTC, marco-vit-pagopa commented on scripts/aws/cfn/microservice-dev-cfg.json
> +    "SelfcarePgUsergroupBaseUrl": "",
@SimoneMartelliNTTD @federicofatica-pagopa  penso che finalmente ci sia un'istanza di SelfCarePG in ambiente dev. 
Va configurato l'URL se vogliamo avere speranza di fare dei test.

2023-04-14 13:41 UTC, SimoneMartelliNTTD commented on scripts/aws/cfn/microservice-dev-cfg.json
> +    "SelfcarePgUsergroupBaseUrl": "",
Ho configurato base URL e API Key.

Piccola nota: a differenza di SelfCare PA (dove il base path è /external/v2) per SelfCare PG il base path è /external/**pn-pg**/v2.

2023-04-17 14:46 UTC, marco-vit-pagopa approved these changes

2023-04-17 15:11 UTC, merged