Feature/pn 1361 be implementare linvio dei messaggi di cortesia su app io ext registry
pagopa/pn-external-registries pull request #19
Opened 2022-06-15 07:03 UTC by masciale89

2022-06-15 07:17 UTC, MTurraPpa requested changes

2022-06-15 07:17 UTC, MTurraPpa commented on docs/openapi/pn-io-message-v1.yaml
> +        - recipientTaxID
metterei anche senderDenomination come obbligatorio

2022-06-15 07:17 UTC, MTurraPpa commented on docs/openapi/pn-io-message-v1.yaml
> +          type: integer
Aggiunti anche due_date (o come l'hanno chiamata su IO)

2022-06-15 09:23 UTC, MTurraPpa requested changes

2022-06-15 09:23 UTC, MTurraPpa commented on docs/openapi/pn-io-message-v1.yaml
> +          description: data di scadenza del pagamento
Specifica con un esempio il formato che si aspetta

2022-06-15 09:23 UTC, MTurraPpa commented on docs/wsclient/io/io-functions-services.yaml
> -    format: UTCISODateFromString
Hai fatto la prova anche lasciando l'originale ma con la versione 6.0.0 del openapi-generator?

2022-06-15 10:34 UTC, masciale89 commented on docs/wsclient/io/io-functions-services.yaml
> -    format: UTCISODateFromString
si ho riportato lo yaml alla versione originale e con la versione 6.0.0 funziona correttamente

2022-06-16 06:38 UTC, MTurraPpa approved these changes

2022-06-16 06:39 UTC, MTurraPpa approved these changes

2022-06-16 06:42 UTC, merged