security fixes #pn-2010
pagopa/pn-external-registries pull request #55
Opened 2022-08-23 14:24 UTC by AndreaCimini90

2022-09-05 12:00 UTC, MTurraPpa requested changes

2022-09-05 12:00 UTC, MTurraPpa commented on src/main/java/it/pagopa/pn/external/registries/services/InfoPaymentService.java
> +            log.error(MSG, e);
So che non è correlato alle tue modifiche, ma già che ci sei possiamo chiamare la costante MSG con un nome più consono? Poi è proprio sempre lo stesso messaggio? Mettiamo nel log un riferimento alla singola operazione (ES: il codice di avviso)

2022-09-06 11:07 UTC, AndreaCimini90 commented on src/main/java/it/pagopa/pn/external/registries/services/InfoPaymentService.java
> +            log.error(MSG, e);
Ho cambiato il nome della variabile e aggiunto il codice avviso nel messaggio di errore

2022-09-06 12:14 UTC, MTurraPpa approved these changes

2022-09-06 13:15 UTC, merged