Feature/pn 2805 checkout
pagopa/pn-external-registries pull request #94
Opened 2022-12-12 15:24 UTC by vincenzo-racca-pa

Implementata API che chiama la nuova di Checkout per il pagamento

2022-12-12 17:05 UTC, MTurraPpa requested changes

2022-12-12 17:05 UTC, MTurraPpa commented on docs/openapi/pn-payment-info-external-v1.yaml
> +        - amount
Attenzione perché anche companyName e description sono obbligatori altrimenti la chiamata alle api di checkout danno 400. Prova.

2022-12-12 17:05 UTC, MTurraPpa commented on docs/openapi/pn-payment-info-external-v1.yaml
> +  /ext-registry/pagopa/v1/makePayment:
invece di _makePayment_ che ne dici di _checkoutCart_?

2022-12-13 12:32 UTC, vincenzo-racca-pa commented on docs/openapi/pn-payment-info-external-v1.yaml
> +      operationId: postMakePayment
fatto

2022-12-13 12:32 UTC, vincenzo-racca-pa commented on docs/openapi/pn-payment-info-external-v1.yaml
> +  /ext-registry/pagopa/v1/makePayment:
concordo, fatto

2022-12-13 12:32 UTC, vincenzo-racca-pa commented on docs/openapi/pn-payment-info-external-v1.yaml
> +        - amount
vero, fixato

2022-12-13 15:01 UTC, MTurraPpa approved these changes

2022-12-13 15:04 UTC, merged